# -*- coding: utf-8 -*-
"""이현정_2주차(week02)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nax7PTyddMLpGFs7rbG62nzbllEUS2so
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.linear_model import Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_selection import RFE

# 실행되지 않는다면 관련 클래스 설치 필요

from google.colab import drive
drive.mount('/content/drive')

# 데이터 로드
data_path ='/content/drive/MyDrive/health.xlsx'
df = pd.read_excel(data_path)

# 데이터 확인
df.head()

# 데이터 기본 정보 출력
print(df.info())
print(df.describe())

"""## **기초 통계 분석**"""

# 기초 통계 분석
print("평균:\n", df.mean())
print("중앙값:\n", df.median())
print("최빈값:\n", df.mode().iloc[0])

"""### **데이터 시각화**

Q1. 시각화 방법을 보고 _____에 관련 코드를 적어주세요
"""

# 산점도
# 키와 무게간 양의 상관관계 확인
plt.scatter(df['height'],df['weight'])

# 히스토그램
f_h=df.loc[df.gender==2,['gender','height']]
m_h=df.loc[df.gender==1,['gender','height']]
plt.hist(f_h['height'],bins=7,alpha=0.5,label='female') #alpha:투명도
plt.hist(m_h['height'],bins=7,alpha=0.5,label='male')
plt.legend()

# 박스플롯 (이상치 확인)
sns.boxplot(data=df,x='gender',y='weight',hue='smoking')

# 히트맵
x= df.loc[:,['weight','waist','cholesterol','HDL','LDL','AST','serum']]
sns.heatmap(x.corr(),annot=True)

# pairplot
sns.pairplot(x)

# 바이올린 플랏
plt.figure(figsize=(12, 6))
sns.violinplot(data=df[['systolic', 'diastolic', 'blood_sugar', 'cholesterol']], palette='muted')
plt.title("Violin Plot of Key Health Metrics")
plt.xticks(rotation=45)
plt.show()

# 밀도 플롯 (Kernel Density Estimation, KDE)
plt.figure(figsize=(12, 6))
sns.kdeplot(df['blood_sugar'], shade=True, color='red', label='Blood Sugar')
sns.kdeplot(df['cholesterol'], shade=True, color='blue', label='Cholesterol')
plt.title("Density Plot of Blood Sugar & Cholesterol")
plt.legend()
plt.show()

"""### **이상치**

Q2.  주제를 보고 빈칸에 적절한 코드를 작성해 완성시켜 주세요
"""

# 이상치 탐색 (IQR 사용)
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
outliers = ((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).sum()
print("이상치 개수:\n", outliers)

"""### **데이터 전처리**

Q3. 주제를 보고 빈칸에 적절한 코드를 작성해 완성시켜 주세요.
"""

# 결측치 처리
## SimpleImputer은 결측치를 채우는 방법을 제공하는 사이킷런의 클래스로, strategy='median'을 사용해 각 열의 중앙값으로 결측치를 채웁니다.
imputer = SimpleImputer(strategy='median')
df.fillna(df.median(), inplace=True)

#이상치 조정
df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]

#범주형 데이터 처리
## include=['object'] 사용하여 범주형 데이터만 선택
## drop_first=True를 사용하여 첫번째 변수 제거-> 더미변수 함정 방지
## 주의!! OneHotEncoder의 경우 drop='first' 파라미터를 사용
categorical_features = df.select_dtypes(include=['object']).columns
df = pd.get_dummies(df, columns=categorical_features,drop_first=True)

# 데이터 전처리 확인
df.info()

df.head()

"""### **변수 선택 (랜덤포레스트 기반)**"""

# y에 가장 큰 영향을 주는 x를 분석하는 것이 목표

# 랜덤포레스트 회귀 작동 원리
#1. 데이터 샘플링 (여러개의 결정트리 생성)
#2. 트리학습 (샘플링된 데이터와 일부 랜덤 선택된 feature만 사용하여 학습)
#3. 결과 평균화 (여러 트리의 결과를 평균내어 최종 값 예측)

from sklearn.metrics import mean_squared_error, r2_score


# 데이터 선택
x = df[['height', 'weight', 'waist', 'blood_sugar',
        'cholesterol', 'triglycerides', 'HDL', 'LDL', 'hemoglobin',
        'smoking', 'drinking', 'oral_check']]
y = df['systolic']

# 모델 학습
model = RandomForestRegressor() #랜덤포레스트회귀모델학습
model.fit(x, y) #x,y 데이터 학습

#예측
y_pred=model.predict(x)

# 변수 중요도 계산 코드
## model 학습을 하면 feature_importances_ 속성 안에 변수중요도값이 저장되어 있습니다.
feature_importances = pd.Series(model.feature_importances_, index=x.columns)

# 출력
print("변수 중요도:\n", feature_importances.sort_values(ascending=False))

"""Q4. x에서 'diastolic' 변수를 포함시키지 않은 이유:

혈압의 종류는 수축기 혈압(systolic)과 이완기 혈압 (diastolic)으로 구분되고,
이중 이미 수축기 혈압을 종속변수로 설정함
둘 중 하나로 고혈압, 저혈압을 판단하기 때문에 만약 이완기 혈압을 독립변수로 설정하면 중복된 결과 유도

Q5. 결과값을 붙여놓고 어떤 변수가 'systolic'과 가장 높은 상관관계를 갖는지 적어주세요.
"""

# 결과값:
#모델성능확인
print("MSE:", mean_squared_error(y, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y, y_pred)))
print("R²:", r2_score(y, y_pred)) #결정계수
# 가장 중요한 변수: waist

"""### **차원 축소 & 스케일링**

Q6. 코드 내에 제시되어 있는 문제에 따라 코드를 작성해주세요.
"""

# 데이터 스케일링 (정규화)
## 평균=0, 분산=1로 변환시키는 코드를 빈칸에 작성해주세요.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

# PCA 객체 생성 및 차원 축소
## n_components는 몇 개의 주성분으로 차원을 축소할 건지 결정합니다.
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# 출력
print("PCA 설명된 분산 비율:", pca.explained_variance_ratio_)

"""Q7. 아래 빈칸을 채워 출력값의 의미를 적어주세요.

A. 첫 번째 주성분(PC1)이 전체 데이터 변동의 약 27%를 설명하고, 두 번째 주성분은 약 17%를 설명합니다.

### **파생 변수**
"""

# 파생 변수 생성 (예시: BMI = 체중(kg) / 키(m)^2)
df['BMI'] = df['weight'] / (df['height'] / 100) ** 2

df[['BMI','weight','height']]

"""Q8. 원하는 파생변수를 생성해주세요.
  예시: 혈압차이, 총 콜레스테롤 비율, 혈당 위험도 등

"""

#총 콜레스트롤 비율

df['total_cholesterol']=df['HDL']+df['LDL']+df['triglycerides']/5
df[['total_cholesterol','HDL','LDL','triglycerides']]