# -*- coding: utf-8 -*-
"""이현정_week06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10NzCArXjirnEd3hpRzHfoyPTvh_rw_yu

# Principal Component Analysis
"""

import numpy as np
import pandas as pd

# 공분산 행렬 정의
Sigma=np.array([[5,4,1,0],[4,6,4,1],[1,4,6,4],[0,1,4,5]])

# 고유값 분해 및 내림차순 정렬
eigvals,eigvecs=np.linalg.eig(Sigma)
idx=np.argsort(eigvals)[::-1]
eigvals=eigvals[idx]
eigvecs=eigvecs[:,idx]

# 각 주성분의 분산 비율
explained_var_ratio=eigvals/np.sum(eigvals)

# 결과 정리
result = pd.DataFrame({
    'A': eigvals,
    'B': explained_var_ratio,
}, index=[f'PC{i+1}' for i in range(len(eigvals))])

print(result)
print(pd.DataFrame(eigvecs, columns=[f'PC{i+1}' for i in range(4)], index=['x1', 'x2', 'x3', 'x4']))

"""### 위 PCA 수행 결과를 보고 다음 빈칸을 모두 채워보세요.
#### Q1. 첫 번째 주성분의 분산 비율 : 0.595008
#### Q2. PC3의 고유값 : 1.909830
#### Q3. PC4를 x1~x4의 선형 결합으로 나타내면? : PC4 = -0371748x1+0601501x2-0.601501x3+0.371748
#### Q4. 두 번째 주성분까지 총 분산 비율 : 0.906558
#### Q5. 분산 비율에 의한 적절한 주성분의 개수 : 2개
#### Q6. Q5에서 그렇게 생각한 이유 : 주성분의 갯수를 결정하는 기준 중 80%이상까지 설명하는 부분을 생각

# Scree Plot
"""

# Scree Plot 그리기
import matplotlib.pyplot as plt
plt.figure(figsize=(6, 4))
plt.plot(range(1, len(eigvals)+1), eigvals, 'o-', linewidth=2)
plt.title('Scree Plot')
plt.xlabel('Principal Component')
plt.ylabel('Eigenvalue (Variance)')
plt.xticks(range(1, len(eigvals)+1))
plt.grid(True)
plt.show()

"""#### Q7. Scree Plot을 바탕으로, 몇 개의 주성분을 선택하는게 적절할지 이유와 함께 적어주세요.
A.3,elbow 기준으로
"""